---
- hosts: localhost
  connection: local

  vars:
   ansible_python_interpreter: /usr/bin/python3
   vnet_name: myVirtualNetwork
   vnet_subnet: "jeremycloudvnet"
   security_group_name: networkSecurityGroup
   resource_group: myResourceGroup2
   public_ip_name: Ipdomain



  tasks:
    - name: Login to azure
      shell: az login --username "{{lookup('env', 'email')}}" --password "{{lookup('env', 'password')}}"
      register: ps

    - name: Ressource group doc
      debug:
        msg: "Go to ressource group doc https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_resourcegroup_module.html"

    - name: Create resource group
      azure_rm_resourcegroup: 
        name: "{{resource_group}}"
        location: westus
        tags:
          testing: testing
          delete: never

    - name: Virtual network
      debug:
        msg: "Go to virtual network doc https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_virtualnetwork_module.html"

    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: myResourceGroup2
        name: "{{vnet_name}}"
        address_prefixes_cidr:
          - 10.1.0.0/16
          - 172.100.0.0/16
        dns_servers:
          - 127.0.0.1
          - 127.0.0.2
        tags:
          testing: testing
          delete: on-exit

    - name: Subnet
      debug:
        msg: "Go to subnet doc https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_subnet_module.html"

    - name: Create subnet
      azure_rm_subnet:
        resource_group: myResourceGroup2
        virtual_network_name: "{{vnet_name}}"
        name: "{{vnet_subnet}}"
        address_prefix_cidr: "10.1.1.0/24"

    - name: Public IP address
      debug:
        msg: "Go to public ip address https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_publicipaddress_module.html"

    - name: Create public IP address
      azure_rm_publicipaddress:
        resource_group: "{{resource_group}}"
        name: "{{ public_ip_name }}"
        allocation_method: static
        state: present
      register: output_ip_address
        #domain_name: vmdebianvirtual
        

      register: output_ip_address

    - name: Network Security Group
      debug:
        msg: "Go to Network Security Group doc https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_securitygroup_module.html"


    - name: Create Network Security Group
      azure_rm_securitygroup:
        resource_group: "{{resource_group}}"
        name: "{{security_group_name}}"

    - name: Network Interface
      debug:
        msg: "Go to network interface doc https://docs.ansible.com/ansible/latest/collections/azure/azcollection/azure_rm_networkinterface_module.html"

    - name: Delete network interface
      azure_rm_networkinterface:
       resource_group: "{{resource_group}}"
       name: nic003
       state: absent

    - name: Create a network interface
      azure_rm_networkinterface:  
        name: myVirtualNetwork
        #name: "{{net_interface_name}}"
        resource_group: "{{resource_group}}"
        virtual_network: "{{vnet_name}}"
        subnet_name: "{{vnet_subnet}}"
        security_group: "{{security_group_name}}"
        ip_configurations:
          - name: default
            public_ip_name: "{{ public_ip_name }}"
            #public_ip_address_name: "{{public_ip_name}}"
            primary: True

    - name: Create your VM
      debug:
        msg: "Go to vm doc https://learn.microsoft.com/en-us/cli/azure/vm?view=azure-cli-latest#az-vm-create"

    - name: Create your windows VM
      shell: |
        az vm create \
          --resource-group "{{resource_group}}" \
          --name testvm12 \
          --image Win2022AzureEditionCore \
          --public-ip-sku Standard \
          --admin-username "{{lookup('env', 'vm_user')}}" \
          --admin-password "{{lookup('env', 'vm_password')}}" \
          --vnet-name "{{vnet_name}}"
          --subnet "{{ vnet_subnet }}"