---
- hosts: localhost
  connection: local

  vars:
    resource_group: ansible-rg
    az_plan_name: appservice-plan
    storage_account_name: "2024baschelor2"

  tasks:
  - name: Login to azure
    shell: az login --username "{{lookup('env', 'email')}}" --password "{{lookup('env', 'password')}}"
    register: ps

  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: eastus

  - name: Create an Azure App Service Plan
    azure_rm_appserviceplan:
      name: "{{az_plan_name}}"
      is_linux: true
      number_of_workers: 1
      resource_group: "{{ resource_group }}"
      sku: S1

  - name: Create a Storage Account for Azure Function
    shell: |
      az storage account create \
        -n {{storage_account_name}} \
        -g {{ resource_group }} \
      -l eastus --sku Standard_LRS
      
    register: output

  - name: Create container based function app
    azure_rm_functionapp:
      resource_group: "{{ resource_group }}"
      name: mario-33000-whoiam
      storage_account: "{{storage_account_name}}"
      plan:
        resource_group: "{{ resource_group }}"
        name: "{{az_plan_name}}"
      container_settings:
        name: maissacrement/azure-functionapp:0.0.1
        registry_server_url: index.docker.io
